language: python
dist: trusty
python:
   - "2.7"
install:
   - sudo apt-get build-dep python-pygame
   - pip install -e .[simulator]
   - pip install -r requirements-dev.txt
script:
   - flake8 earthstar
   - flake8 tests
   - pytest tests
